### PR TITLE
Added support for WCH(Jiangsu Qin Heng) CH422G I/O Expander

### PR DESCRIPTION
**Pull request by lboue**
Added support for **WCH(Jiangsu Qin Heng) CH422G** I/O Expander:
- Manufacturer WCH(Jiangsu Qin Heng)
- Mfr. Part # CH422G
- LCSC Part # C57543
- Package SOP-16
- Description 8 * 1MHz SOP-16 I/O Expanders
- [Datasheet](https://www.lcsc.com/datasheet/lcsc_datasheet_2403131123_WCH-Jiangsu-Qin-Heng-CH422G_C57543.pdf)

### CODE REVIEW

**Comment by Lzw655** [comment]
Hi @lboue, thank you for the contributions. 

There are several places such as README, lib version need to be modified. May I change some of these places based on your commit to a new PR?

**Comment by lboue** [comment]
@Lzw655 
Of course you can. Please.

**Comment by Lzw655** [comment]
Hi @lboue, please check the new PR and help me test it. If everything is ok, then we can merge it and release a new version to the Arduino Library.

**Comment by lboue** [comment]
Thanks @Lzw655. I'll get the tests done as soon as possible.

**Comment by lboue** [comment]
@Lzw655
This CH422G test file is working with arduino-esp3 3.0.0-alpha3 release: [CH422G_Test_3.0.0-alpha3.ino](https://github.com/lboue/ESP32_IO_Expander/blob/CH422_test/examples/TestFunctions/CH422G_Test_3.0.0-alpha3.ino)

**Pull request closed without merging**
